### ISSUE TITLE
Is this a WCA-approved scramble?

### ISSUE THREAD

**Issue by zaynv** [nickcolley/scrambo#34]
Does this algorithm produce a "random-state scramble"?

**Comment by NickColley** [comment]
I think some of the algorithms used will but others not, I have not investigated that so I can't be sure sorry :)

**Comment by coder13** [comment]
No. While these are directly pulled from jsss, this is not tnoodle and WCA has only approved tnoodle to be used to generate competition official scrambles.

**Comment by NickColley** [comment]
Good to know thanks @coder13 !

**Comment by zaynv** [comment]
Oh I see, but even if it isn't a WCA approved scramble, it is still a "random state scramble" right? Mainly asking because I wanted to try to use it when making a cubing app.

**Comment by coder13** [comment]
Yes, I failed to mention this. I don't think the 4x4 one is random state but 2x2 and 3x3 are.
